baseurl      = "https://remixco.org/"
languageCode = "zh-cn"
title        = "Remixco's Lab"
hasCJKLanguage = true

[outputs]
    home = ["HTML", "RSS", "JSON"]
    page = ["HTML"]
    section = ["HTML"]

[pagination]
    pageSize = 5

# 这里是给搜索框的“强心针”
[params.search]
    enabled = true
    type = "json"
    indexURL = "/index.json"
