baseURL = "https://remixco.org/"
languageCode = "zh-cn"
title = "Remixco's Lab"
hasCJKLanguage = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML"]

[pagination]
  pageSize = 5

[params.search]
  enabled = true
  type = "json"
  indexURL = "/index.json"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
