[[main]]
    name = "主页"
    url = "/"
    weight = 10
    [main.params]
        icon = "home"

[[main]]
    name = "档案"
    url = "/archives/"
    weight = 20
    [main.params]
        icon = "archive"

[[main]]
    name = "搜索"
    url = "/search/"
    weight = 30
    [main.params]
        icon = "search"

[[main]]
    name = "关于我"
    url = "/about/"
    weight = 40
    [main.params]
        icon = "user"

[[main]]
    name = "隐私政策"
    url = "/privacy/"
    weight = 50
    [main.params]
        icon = "shield"
