[footer]
  since = 2026
  customText = "Remixco. 版权所有。"

[sidebar]
  emoji = "🚀"
  subtitle = "数字生活折腾家，专注家庭实验室与自动化运维。"
  avatar = "img/mia.png"

[article]
  math = false
  readingTime = true

[colorScheme]
  toggle = true
  default = "dark"

[googleAdsense]
  enabled = true
  client = "ca-pub-5936544039418820"
